### ISSUE TITLE
Apparent issue with multiprocessing

### ISSUE THREAD

**Issue by kwinners** [Roastero/freshroastsr700#38]
Using a Windows 10 box, with Anaconda 3.7.  
Installed version 0.2.4

Returns:
/ ____| __ \|____ / _ \ / _ \
| (___ | |__) | / / | | | | | |
\___ \| _ / / /| | | | | | |
____) | | \ \ / / | |_| | |_| |
|_____/|_| \_\/_/ \___/ \___/
/\ | | (_)
/ \ _ __| |_ _ ___ __ _ _ __
/ /\ \ | '__| __| / __|/ _` | '_ \
/ ____ \| | | |_| \__ \ (_| | | | |
/_/ ___\_\_| \__|_|___/\__,_|_| |_|
/ ____|
| (___ ___ _ ____ _____ _ __
\___ \ / _ \ '__\ \ / / _ \ '__|
____) | __/ | \ V / __/ |
|_____/ \___|_| \_/ \___|_|

SR700 Artisan Server - Luca Pinello 2019 (@lucapinello)

Send bugs, suggestions or *green coffee* to lucapinello AT gmail DOT com

-[ Starting Nameserver... ]-
-[ Starting Server... ]-
-[ Initializing connection with the SR700... ]-
-[ can't pickle weakref objects ]-

Send bugs, suggestions or *green coffee* to lucapinello AT gmail DOT com

Bye!

PS C:\python\Lib\site-packages> Traceback (most recent call last):
File "<string>", line 1, in <module>
File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
new_handle = reduction.steal_handle(parent_pid, pipe_handle)
File "c:\python\lib\multiprocessing\reduction.py", line 82, in steal_handle
_winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect

**Comment by lucapinello** [comment]
Using Python 3.5 should solve this.
